server:
  port: 7070

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

# Gateway routes
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: service-a-route
          uri: lb://service-a
          predicates:
            - Path=/service-a/**
          filters:
            - StripPrefix=1

        - id: service-b-route
          uri: lb://service-b
          predicates:
            - Path=/service-b/**
          filters:
            - StripPrefix=1